# Generated by Django 3.1.1 on 2020-09-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='favorite',
        ),
    ]
